name: Sync Instagram -> JSON

on:
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes
  workflow_dispatch: {}       # allow manual runs

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch latest Instagram post (Graph API)
        env:
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
        run: node assets/scripts/fetch-instagram-graph.cjs

      - name: Commit & push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/data/instagram.json
          git commit -m "chore: update instagram.json" || echo "No changes to commit"
          git push
